# Content for the swarmery site. Copy follows the product: plain, concrete, no hype.
import json

REPO = "https://github.com/atretyak1985/swarmery"
SUBSTACK = "https://swarmery.substack.com"
X = "https://x.com/SwarmeryDev"

FEATURES = [
  dict(
    slug="planning", n=1, name="Planning", ep="ep1-planning", dur="1:54",
    kicker="From an idea to a plan your agents can run",
    title="Agents write code fast. Planning makes them build <em>what you meant</em>.",
    lede="Describe what you want in plain words. A planner reads your repo, interviews you one question at a time, and writes a phased plan with acceptance criteria and forecasts. The same page runs it, one phase at a time or the whole graph, each phase in its own git worktree.",
    menu="An interview that ends in a phased plan",
    beats=[
      ("the interview", "An interview, not a form",
       "The planner asks one question at a time on the left, while the plan as it stands sits on the right. Every option comes with pros, cons and a recommended pick. Pick several, or answer in your own words: a reply the wizard cannot parse turns into a conversation instead of a dead end.",
       ["The running plan rebuilds after every answer", "Every answer and its reasoning is kept in the plan", "Refine, or tell the planner to proceed"],
       "plan-interview", "127.0.0.1:7777/plans/new"),
      ("the plan", "Markdown stays the source of truth",
       "A plan lands as plain docs in your private workspace: the goal, the decisions from the interview, and phases with their sizes and what each one depends on. Progress is the acceptance-criteria checkboxes inside them, and ticking one in the dashboard rewrites that exact line.",
       ["Each phase is a markdown doc with acceptance criteria", "Pick a model per phase, run one phase or the whole plan", "A finished phase writes a report of what shipped"],
       "plan-lands", "127.0.0.1:7777/plans/trail-sharing"),
      ("forecast vs reality", "Forecast first, then measure",
       "Before anything runs, the planner forecasts each phase's size, duration, outcome and the areas it will touch. Afterwards the actuals are scored against the forecast. When a phase fails, the planner proposes a fix, and you review the revision as a diff before anything changes.",
       ["See where a phase went off plan", "Revisions are staged proposals until you apply them", "A run that lands far from the plan becomes a lesson candidate"],
       "plan-revision", "127.0.0.1:7777/plans/trail-sharing/revisions"),
    ],
    shots=["01-planning-1-interview1-pros", "01-planning-2-interview2", "01-planning-3-readme", "01-planning-4-revisions"],
    chapters=[("0:00","Agents guess what you meant"),("0:10","Start with an idea"),("0:15","The planner interviews you"),("0:25","Pros, cons and a pick"),("0:35","The plan rebuilds after every answer"),("0:45","The plan lands as docs"),("0:50","Phases and dependencies"),("0:55","Run one phase or the whole plan"),("1:05","Acceptance criteria"),("1:15","Report of what shipped"),("1:20","Forecast vs reality"),("1:30","A failed phase gets a fix"),("1:35","Review the revision as a diff"),("1:40","Summary, spec and every phase")],
  ),
  dict(
    slug="inbox", n=2, name="Inbox", ep="ep2-inbox", dur="1:47",
    kicker="Every decision your agents wait on, in one place",
    title="Your agents stop and wait. <em>One queue</em> for every decision.",
    lede="A permission prompt in one terminal, a question in another. The Inbox puts every decision that waits on you in one list you work from the keyboard, and an agent clears the part that never needed you.",
    menu="Approvals, questions and proposals in one queue",
    beats=[
      ("one queue", "Six kinds, one list",
       "Approvals, agent questions, lessons, advisor findings, agent-change proposals and classifier checks, split by tab or shown together. Pick on the left, act on the right: j and k move, e takes the primary action, x denies or dismisses.",
       ["Approvals show the tool, its input, the session and a countdown", "Questions come as real choices, not a yes or no", "Alerts say that work has stopped, and what to do"],
       "inbox-queue", "127.0.0.1:7777/inbox"),
      ("lessons", "When a run surprises the planner",
       "A run that lands far from its forecast drafts a lesson with the cause and the agent's suggestion. Accept it, and future runs in that area get it in their brief. Lessons that stop helping are proposed for retirement.",
       ["Every lesson cites what happened in the run", "Nothing becomes active without your accept", "The Advisor spots patterns in your runs, with evidence"],
       "inbox-lesson", "127.0.0.1:7777/inbox?tab=lessons"),
      ("agent changes", "Rewrites you review as a diff",
       "Swarmery can draft a rewrite of an agent from its failed runs. It arrives in the Inbox as a diff, and nothing changes until you approve it. A triage agent works the backlog and leaves suggestions; what it closed stays visible for a week, with an undo.",
       ["Approvals, agent changes and alerts always wait for you", "One click turns advice into a task for an agent", "A local model labels sessions, and you check it now and then"],
       "inbox-rewrite", "127.0.0.1:7777/inbox?tab=proposals"),
    ],
    shots=["02-inbox-1-all", "02-inbox-2-askq", "02-inbox-3-lesson", "02-inbox-4-proposal"],
    chapters=[("0:00","Your agents wait for you"),("0:10","One queue for every decision"),("0:20","Keyboard: j, k, e, x"),("0:25","Approvals with a countdown"),("0:30","Questions as real choices"),("0:35","Alerts"),("0:40","A run drafts a lesson"),("0:45","Accept it for future runs"),("0:50","Retiring lessons"),("0:55","The Advisor, with evidence"),("1:05","Agent rewrites from failed runs"),("1:10","Review it as a diff"),("1:15","The local classifier"),("1:25","A triage agent"),("1:30","A week of undo")],
  ),
  dict(
    slug="health", n=3, name="Health", ep="ep3-health", dur="1:23",
    kicker="How your agents are doing, and what to change",
    title="Agents rarely fail loudly. See the pattern, <em>change one thing</em>.",
    lede="A retry here, a lint error there. Health reduces a date range to one sentence about the fleet and the agents that moved it, names the friction you can remove today, and turns patterns into recommendations with the evidence attached.",
    menu="Scorecards, friction, cost and an advisor",
    beats=[
      ("overview", "One sentence about the fleet",
       "One strip says what this window looks like, what waits on you and what you changed. Below it, the agents that moved the number, and the friction you can remove today in one click.",
       ["Per-agent scorecards against the previous window", "Errors split into behaviour, harness and infra", "Estimates checked against actual hours, per task"],
       "health-overview", "127.0.0.1:7777/health"),
      ("friction", "What cost you time",
       "Which tools you keep denying, each one click from a rule. Repeated errors, and how long agents waited on you. Lessons from retros, grouped by how often they repeat.",
       ["A denied tool is one click from an auto-approve rule", "A triage run mutes noise and files a fix task", "Approval wait time, per session"],
       "health-friction", "127.0.0.1:7777/health/friction"),
      ("cost", "Know the cost before the bill does",
       "What you spent, what drove it, and where the month is heading. Split it by project, model or agent, and export it as CSV. Productivity and autonomy sit beside the spend.",
       ["Cost and tokens against the live quota window", "A projected monthly figure", "The Advisor turns patterns into recommendations"],
       "health-cost", "127.0.0.1:7777/health/cost"),
    ],
    shots=["03-health-1-overview", "03-health-2-agents", "03-health-3-friction2", "03-health-4-advisor"],
    chapters=[("0:00","Agents rarely fail loudly"),("0:10","One strip for the window"),("0:15","One sentence about the fleet"),("0:20","Friction you can remove today"),("0:25","Agent scorecards"),("0:30","Denied tools"),("0:35","Repeated errors and waiting"),("0:40","Lessons from retros"),("0:45","Estimates vs actual hours"),("0:50","The Advisor"),("1:00","Cost and tokens"),("1:05","Split by project, model, agent")],
  ),
  dict(
    slug="sessions", n=4, name="Sessions", ep="ep4-sessions", dur="1:27",
    kicker="Every Claude Code session, across every project",
    title="Five sessions, three repos. Know which one is <em>waiting on you</em>.",
    lede="The daemon reads the transcripts Claude Code already writes and indexes them as they land. A list that tells working from stuck, a detail view that replays the run as a conversation, and a rail with models, agents, files and cost. Nothing to install in your projects.",
    menu="Every session live: chat, timeline, diffs",
    beats=[
      ("the list", "Working, or only quiet",
       "Every session from every project, newest first. Filter by status: working, waiting, idle, done. Each row shows its branch, model and plan progress, and a live row says what the agent is doing this second.",
       ["A stuck session shows how long it has been silent", "Plan runs collapse into one card per plan", "Filter by status and account"],
       "sessions-list", "127.0.0.1:7777/sessions"),
      ("the timeline", "Every tool call, in order",
       "Chat reads like a conversation with tool calls folded away, and you can reply to the agent right from the dashboard. Timeline shows every tool call, sub-agents and errors. A permission waits right in line: approve it there.",
       ["Reply from the dashboard to resume a session", "Sub-agents included in the timeline", "A waiting session tells you where to answer"],
       "sessions-timeline", "127.0.0.1:7777/sessions/migrate-email-templates"),
      ("the diffs", "Every file the session changed",
       "Diffs collects every file the session touched, in one place. Changes outside the plan are flagged as out of scope. A handoff brief lets a fresh session pick up where the last one stopped.",
       ["Out-of-plan changes flagged", "Models, agents, skills and the call tree in the side panel", "Handoff brief for a fresh session"],
       "sessions-diffs", "127.0.0.1:7777/sessions/migrate-email-templates/diffs"),
    ],
    shots=["04-sessions-1-list", "04-sessions-2-chattop", "04-sessions-3-timeline", "04-sessions-4-diffs"],
    chapters=[("0:00","Five sessions, three repos"),("0:10","Every session, newest first"),("0:15","Filter by status"),("0:20","Branch, model, plan progress"),("0:25","Open one session"),("0:30","Chat"),("0:35","Reply from the dashboard"),("0:40","Timeline"),("0:45","Approve in line"),("0:50","Diffs"),("0:55","Out-of-scope changes"),("1:00","Side panel"),("1:05","Handoff brief"),("1:10","Waiting sessions"),("1:15","Nothing to install")],
  ),
  dict(
    slug="learning", n=5, name="Learning", ep="ep5-learning", dur="1:21",
    kicker="What your agents learned, and whether to trust it",
    title="Agents repeat the same mistake. Make them <em>learn from every run</em>.",
    lede="Forecasts sound confident, and miss. A run that lands far from its forecast becomes a lesson candidate with the evidence attached. Nothing becomes active without your accept, every active lesson is re-measured, and the local classifier only acts once it has earned it.",
    menu="Lessons, a local classifier, forecast honesty",
    beats=[
      ("lessons", "Earned, accepted, re-measured",
       "When a run lands far from its forecast, Swarmery drafts a lesson. Each one cites its cause and the evidence from that run, and it reaches future runs only after you accept it. Lessons are re-measured, and one that stops helping is retired.",
       ["Active lessons reach runs that touch their area", "Every lesson carries a measured effect", "Retirement proposals when a lesson stops earning its place"],
       "learning-lessons", "127.0.0.1:7777/learning"),
      ("the classifier", "Watching before acting",
       "A small local model reads each finished session and answers a few fixed questions: how the run ended, what kind of task it was, why it failed. You check its answers and see how often it matches you. Off, watching, acting: it acts only once it has earned it.",
       ["Runs on your machine", "Agreement rate per question", "Its answers go to the Inbox for checking"],
       "learning-classifier", "127.0.0.1:7777/learning/classifier"),
      ("forecast honesty", "Does the plan keep its word",
       "Every phase starts with a forecast. Did it hold? Group by model or agent and see who over-promises. Routing shows which model would have been the right pick: here a cheaper model did the same work for a fifth of the cost.",
       ["Calibration by model, effort, agent or project", "Declared confidence against reality", "Proof: what your decisions actually changed"],
       "learning-honesty", "127.0.0.1:7777/learning/honesty"),
    ],
    shots=["05-learning-1-lessons", "05-learning-2-classifier", "05-learning-3-honesty-agent", "05-learning-4-routing"],
    chapters=[("0:00","The same mistake, again"),("0:10","A run drafts a lesson"),("0:15","Cause and evidence"),("0:20","Only after you accept"),("0:30","Re-measured, then retired"),("0:40","The local classifier"),("0:45","Off, watching, acting"),("0:50","Did the forecast hold?"),("0:55","Who over-promises"),("1:00","Routing: the right model"),("1:05","A fifth of the cost")],
  ),
  dict(
    slug="knowledge", n=6, name="Knowledge", ep="ep6-knowledge", dur="1:21", soon=True,
    kicker="What one project knows about itself",
    title="Every new session starts from zero. Give it <em>what the project already knows</em>.",
    lede="A session re-reads the repo and guesses the architecture. Knowledge keeps what one project knows about itself in one place: its memory files in one editor, an architecture map that says how stale it is, and code graphs agents can query instead of grepping.",
    menu="Memory, architecture map and code graph",
    beats=[
      ("memory", "Instructions and memory, in one editor",
       "Project instructions, auto-memory and Serena notes in one editor. Edit, preview, save: every save keeps a backup. A stale-fact lint catches memory that disagrees with the repo, like a PR the memory calls open when git says it merged.",
       ["A conflict guard on every save", "Finished entries move out of the index agents always load", "Stale facts flagged against git"],
       "knowledge-memory", "127.0.0.1:7777/knowledge/memory"),
      ("architecture", "A map of the repo, with a staleness badge",
       "An architecture map of the repo: modules by layer (UI, domain, data, server), and flows you can trace step by step, file by file. The map says how stale it is, per commit.",
       ["Machine-readable layers, modules and flows", "Pick a flow and follow every step", "Freshness stamped per commit"],
       "knowledge-arch", "127.0.0.1:7777/knowledge/architecture"),
      ("code graph", "Real symbols, not grep",
       "Serena gives agents a language server, and the dashboard shows which tools they call. Graphify turns the code into a graph of communities: click any symbol to see what it touches.",
       ["Symbol-level search and references", "A graph of communities", "What a symbol touches, one click away"],
       "knowledge-graph", "127.0.0.1:7777/knowledge/graphify"),
    ],
    shots=["06-knowledge-1-memory-preview", "06-knowledge-2-arch-flow", "06-knowledge-4-graphify-node"],
    chapters=[("0:00","Every session starts from zero"),("0:10","Memory in one editor"),("0:15","Every save keeps a backup"),("0:20","Stale facts"),("0:25","What agents always load"),("0:30","Architecture map"),("0:35","Modules by layer"),("0:40","A flow, file by file"),("0:50","Serena: real symbols"),("0:55","Tools your agents call"),("1:00","Graphify"),("1:05","What a symbol touches")],
  ),
]

PROMO = dict(title="Swarmery in 75 seconds", dur="1:15", file="swarmery-promo.mp4", poster="promo",
  text="Which agent is stuck right now? One control plane for all your Claude Code sessions: every session live, every decision in one queue, plans your agents can run, and the cost before the bill.",
  chapters=[("0:00","Which agent is stuck right now?"),("0:15","One control plane"),("0:20","Every session, every project, live"),("0:25","Who is waiting for you"),("0:30","Plan it, phase it, hand it off"),("0:40","Know the cost before the bill"),("0:47","One set of agents, every project"),("1:00","One Go binary, on your machine")])

CAPTIONS = {}
SHOT_CAPTIONS = {'00-overview-1-today': 'Today: the whole loop this week, live sessions and what waits on you',
  '00-overview-2-sessions': 'Every Claude Code session across projects, with status, branch and plan progress',
  '00-overview-3-board': 'Board: tasks move from Inbox to Working to Review',
  '00-overview-4-inbox': 'Inbox: one queue for approvals and decisions',
  '01-planning-1-interview1-pros': 'The planner interviews you: options with pros, cons and a recommended pick',
  '01-planning-2-interview2': 'Answer, and the running plan rebuilds next to the question',
  '01-planning-3-readme': 'The plan lands as docs: goal, decisions from the interview, phases and dependencies',
  '01-planning-4-revisions': 'A failed phase gets a proposed fix, reviewed as a diff',
  '02-inbox-1-all': 'Every decision that waits on you, in one queue',
  '02-inbox-2-askq': 'Agent questions as real choices, not a yes or no',
  '02-inbox-3-lesson': "A lesson drafted from a run that went off plan, with the agent's suggestion", '02-inbox-4-proposal': 'An agent rewrite drafted from its failed runs, as a diff to approve',
  '03-health-1-overview': 'One sentence about the fleet, and friction you can remove today',
  '03-health-2-agents': 'Per-agent scorecards compared with the previous window',
  '03-health-3-friction2': 'Denied tools, repeated errors, and time agents waited on you',
  '03-health-4-advisor': 'Advisor recommendations with evidence, and agent proposals',
  '04-sessions-1-list': 'All sessions, filtered by status and account',
  '04-sessions-2-chattop': 'One session: status, cost, chat and the side panel',
  '04-sessions-3-timeline': 'Timeline: every tool call, with an approval waiting in line',
  '04-sessions-4-diffs': 'Diffs: every file changed, changes outside the plan flagged',
  '05-learning-1-lessons': 'Lesson candidates with cause and evidence, and a retirement proposal',
  '05-learning-2-classifier': 'The local classifier and how often it matches you',
  '05-learning-3-honesty-agent': 'Forecast honesty by agent: who over-promises',
  '05-learning-4-routing': 'Routing: which model would have been the right pick',
  '06-knowledge-1-memory-preview': 'Memory: project instructions, auto-memory and Serena notes in one editor',
  '06-knowledge-2-arch-flow': 'Architecture map with a flow traced step by step',
  '06-knowledge-3-serena-x': 'Serena dashboard embedded for the project',
  '06-knowledge-4-graphify-node': 'Graphify code graph: a symbol and everything it touches'}
POSTS = [
  ("2026-10-07", "Why my weekly limit ran out in the middle of the week, and what I did about it",
   "I thought agents were eating my tokens. It turned out to be one habit, and that habit can be broken.",
   "https://swarmery.substack.com/p/why-my-weekly-limit-ran-out-in-the",
   "18b24b37-189d-498c-9e5e-37d9a38c09ba_1728x1152.jpeg", "cost"),
  ("2026-09-29", "Why I Don't Believe an Agent When It Says \"Done\"",
   "Before lessons and forecasts, the one thing it all stands on: a model's work has to be checked from the outside, not taken on its own word.",
   "https://swarmery.substack.com/p/why-i-dont-believe-an-agent-when",
   "88ea9b5f-2f53-4bf3-bfbc-6492a98d7bd7_1792x1008.jpeg", "verification"),
  ("2026-09-28", "How Swarmery Came to Be. Part 3: How the Agent System Stopped Being a Black Box",
   "How I started to see what my agents are really doing, and how the system learns from its own work.",
   "https://swarmery.substack.com/p/how-swarmery-came-to-be-part-3-how",
   "70b8a0f1-2694-4a04-9de3-b6551655a592_1664x1184.jpeg", "origin · part 3"),
  ("2026-09-28", "How Swarmery Came to Be. Part 2: Why I Replaced the Kanban Board with Plans",
   "Why cards on a board did not work for my agents, and how the planner became the heart of Swarmery.",
   "https://swarmery.substack.com/p/how-swarmery-came-to-be-part-2-why",
   "ce7c7773-2d1c-4f87-9275-b0a5840e5c00_1792x1008.jpeg", "origin · part 2"),
  ("2026-09-28", "How Swarmery Came to Be. Part 1: From ChatGPT to Claude Code",
   "",
   "https://swarmery.substack.com/p/how-swarmery-came-to-be-part-1-from",
   "1c30b3eb-a692-4d38-8d38-605146b6724f_1792x1008.jpeg", "origin · part 1"),
  ("2026-09-23", "What a Book from 2004 Taught Me About My Agents",
   "How to tell if an agent really understood the task, and how a system can learn when the model can't.",
   "https://swarmery.substack.com/p/what-a-book-from-2004-taught-me-about",
   "b145c49e-5c86-4804-a794-55329aed5cf0_1792x1008.jpeg", "learning"),
  ("2026-08-31", "Retro: The Agent System That Improves Itself",
   "How my agent system learned to learn from its own mistakes.",
   "https://swarmery.substack.com/p/retro-the-agent-system-that-improves",
   "0f8d402c-aa5c-48ad-b07f-91f717f88fd9_1100x738.webp", "retro"),
  ("2026-07-24", "Swarmery: How I Stopped Copy-Pasting Agents Between Projects, and Started Driving Them",
   "Syncing agents was the easy part. The interesting problems started after: seeing what 15 agents across 6 projects actually do, measuring whether they're any good, and letting a board drive them.",
   "https://swarmery.substack.com/p/swarmery-how-i-stopped-copy-pasting",
   "3c90fa4a-6e49-4426-9a9e-273789b506ef_1280x720.jpeg", "the first post"),
]
def cover(fn, w=800):
    return ("https://substackcdn.com/image/fetch/w_%d,c_limit,f_auto,q_auto:good,fl_progressive:steep/"
            "https%%3A%%2F%%2Fsubstack-post-media.s3.amazonaws.com%%2Fpublic%%2Fimages%%2F%s" % (w, fn))

PACK_GROUPS = {
  "uav-pack": "domain", "iot-pack": "domain", "web-pack": "domain", "infra-pack": "domain",
  "lsp-pack": "code intelligence", "graft-pack": "code intelligence", "graphify-pack": "code intelligence", "architecture-pack": "code intelligence",
  "jira-pack": "workflow", "review-pack": "workflow", "design-pack": "workflow", "accounts-pack": "workflow",
  "claude-eng-pack": "agent engineering",
}

PRINCIPLES = [
  ("neutrality", "A core that names no one", "Brand tokens are forbidden anywhere under <code>plugins/</code>, and a CI ratchet keeps the count at zero. Each project's flavor arrives at runtime from its own <code>project.json</code>."),
  ("graduation", "Flow goes up only", "A component is born project-local, moves to a domain pack when a second project needs it, and reaches the core only when every project does. Nothing is copied downward."),
  ("isolation", "One worktree per run", "Every phase run and every dispatched task gets its own branch in an isolated git worktree. Your working tree is never the agent's workspace."),
  ("verification", "Verdicts that can say no", "A read-only verifier diffs the work against the persisted start point and returns PASS, FAIL or INCONCLUSIVE. Done means the criteria are ticked and the report is written, not that a process exited 0."),
  ("plans", "A phase graph, not a wish list", "Every phase carries measurable acceptance criteria, a forecast and a completion report. Runs execute the graph in dependency order, and the markdown on disk stays the source of truth."),
  ("observability", "Everything on the record", "Every session transcript is indexed into local SQLite: tokens, cost, approvals, forecasts against actuals, and the lessons drawn from the gap. Nothing leaves the machine."),
]

CP_PAGES = [
  ("Today", "What waits on you, what runs now, and this week's loop: plan, run, measure, learn, change."),
  ("Inbox", "Every decision in one queue, and it reaches your phone, so a waiting run is unblocked without going back to the desk."),
  ("Sessions", "Every transcript indexed as it is written, with the tool calls, files and errors of each run."),
  ("Needs you", "Every session blocked on a human, oldest first, with the reply ready for your clipboard."),
  ("Plans", "The planner interview, the phase timeline with its dependencies, forecasts, runs and completion reports."),
  ("Health", "Agent scorecards, friction, estimates, an evidenced advisor, and cost against the live quota window."),
  ("Learning", "Lessons from runs that missed their forecast, a local classifier, and how honest the forecasts are."),
  ("Knowledge", "Memory files in one editor with a conflict guard, a stale-fact lint, and the architecture map."),
  ("System", "Every agent, skill, hook and command on the machine, with origin and a content-addressed version history."),
]
