#!/bin/bash
# Protect Sensitive Files Hook for Claude Code
# Blocks edits to sensitive files and directories

set -e

# Read JSON input from stdin
input=$(cat)

# Extract file path using jq
file_path=$(echo "$input" | jq -r '.tool_input.file_path // .tool_input.path // empty')

# Exit if no file path
if [ -z "$file_path" ]; then
  exit 0
fi

# Protected directory names — blocked only when they appear as a full
# path segment, so e.g. skills/docker-build/ is NOT mistaken for build/.
protected_dirs=(
  ".git"
  "node_modules"
  "dist"
  "build"
  ".next"
  "coverage"
)

# Protected files — lock files match by exact basename.
protected_files=(
  "package-lock.json"
  "yarn.lock"
  "pnpm-lock.yaml"
)

base_name=$(basename "$file_path")

# Block edits to files inside a protected directory (path-segment match,
# not substring — anchored by a leading "/" or the start of the path).
# Block messages go to STDERR because only STDERR reaches the model.
for dir in "${protected_dirs[@]}"; do
  if [[ "$file_path" == "$dir/"* || "$file_path" == *"/$dir/"* ]]; then
    echo "🚫 BLOCKED: Cannot modify file inside protected directory: $file_path" >&2
    echo "Protected directory: $dir/" >&2
    echo "" >&2
    echo "If you need to modify this file, please do it manually." >&2
    exit 2  # Exit code 2 blocks the operation
  fi
done

# Block edits to protected lock files (exact basename match).
for f in "${protected_files[@]}"; do
  if [[ "$base_name" == "$f" ]]; then
    echo "🚫 BLOCKED: Cannot modify protected file: $file_path" >&2
    echo "Protected pattern: $f" >&2
    echo "" >&2
    echo "If you need to modify this file, please do it manually." >&2
    exit 2  # Exit code 2 blocks the operation
  fi
done

# Block edits to any .env* file (basename prefix match — covers
# .env, .env.local, .env.production, .env.example, …).
if [[ "$base_name" == .env* ]]; then
  echo "🚫 BLOCKED: Cannot modify protected file: $file_path" >&2
  echo "Protected pattern: .env*" >&2
  echo "" >&2
  echo "If you need to modify this file, please do it manually." >&2
  exit 2  # Exit code 2 blocks the operation
fi

# Block edits to production / populated values files. Documented in rules/NEVER.md.
# Pattern matches values.prod.yaml, values.prod.yml, *.populated.yaml, *.populated.yml.
if [[ "$base_name" == values.prod.yaml || "$base_name" == values.prod.yml ]]; then
  echo "🚫 BLOCKED: Cannot modify production values file: $file_path" >&2
  echo "Protected pattern: values.prod.{yaml,yml}" >&2
  echo "" >&2
  echo "Production values changes require joint specialist + @sre-orchestrator review" >&2
  echo "and explicit user approval per rules/ASK.md." >&2
  echo "If this is a legitimate change, edit manually outside of an agent session." >&2
  exit 2
fi

if [[ "$base_name" == *.populated.yaml || "$base_name" == *.populated.yml ]]; then
  echo "🚫 BLOCKED: Cannot modify populated (rendered-with-secrets) values file: $file_path" >&2
  echo "Protected pattern: *.populated.{yaml,yml}" >&2
  echo "" >&2
  echo "These files are generated by secret-bootstrap scripts and contain rendered" >&2
  echo "secrets. They are gitignored and must never be hand-edited." >&2
  exit 2
fi

# Block edits to generated router/network configs (may contain private keys + PSKs).
if [[ "$file_path" == *"/output/"* && "$base_name" == *.rsc ]]; then
  echo "🚫 BLOCKED: Cannot modify generated network config: $file_path" >&2
  echo "Protected pattern: */output/*.rsc" >&2
  echo "" >&2
  echo "These files are generated by scripts/generate-*.sh and contain secrets." >&2
  echo "Re-run the generator script instead of hand-editing." >&2
  exit 2
fi

# Block edits to Terraform state files.
if [[ "$base_name" == terraform.tfstate || "$base_name" == terraform.tfstate.backup || "$base_name" == *.tfstate || "$base_name" == *.tfstate.backup ]]; then
  echo "🚫 BLOCKED: Cannot modify Terraform state: $file_path" >&2
  echo "Protected pattern: *.tfstate(.backup)?" >&2
  echo "" >&2
  echo "Live infrastructure state is managed by 'terraform apply'; never edit by hand." >&2
  exit 2
fi

# Warn on hand-edits to generated wiki pages (agents/docs/generated/, also reachable as
# .claude/docs/generated/ via the symlink). Regeneration-only zone — same rule as
# agents-index.json. README.md at the tree root stays hand-editable.
# WARN-MODE BURN-IN (gate-hardening rule 1, added 2026-07-06): logs + exit 0 for ~1 week;
# flip to `exit 2` on/after 2026-07-13 if no false positives in the metrics log.
if [[ ("$file_path" == *"agents/docs/generated/"* || "$file_path" == *".claude/docs/generated/"*) && "$base_name" != "README.md" ]]; then
  echo "⚠️  WARN (enforce from 2026-07-13): hand-editing a generated wiki page: $file_path" >&2
  echo "This tree is regeneration-only (see agents/docs/generated/README.md)." >&2
  echo "Fix the source code or the generator prompt, then re-run the wiki generator." >&2
  if [ -n "${AGENT_PROJECT:-}" ]; then
    metrics_dir="${AGENT_WORKSPACE_ROOT:-/Volumes/Work/swarmery-workspace}/${AGENT_PROJECT}/workspace/metrics"
  else
    metrics_dir="${CLAUDE_PROJECT_DIR:-.}/.claude-workspace/metrics"
  fi
  mkdir -p "$metrics_dir" 2>/dev/null || true
  printf '{"ts":"%s","hook":"protect-sensitive-files","stanza":"generated-wiki","mode":"warn","file":"%s"}\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$file_path" >> "$metrics_dir/gate-bypasses.jsonl" 2>/dev/null || true
  exit 0
fi

# Block loose task/plan artifacts dropped DIRECTLY in the workspace root.
# Task artifacts belong in .claude-workspace/working/YYYY/MM/DD/<slug>/ (rules/ALWAYS.md),
# never loose at the meta-repo root. Only the root level itself is guarded — files nested
# under .claude-workspace/ or inside a repo subdirectory are untouched, and non-artifact
# .md files (CLAUDE.md, README.md, …) stay writable.
#
# The workspace root is the directory that contains .claude-workspace. Prefer
# $CLAUDE_PROJECT_DIR; fall back to the file's own parent directory (path heuristic).
#
# Canonicalize a relative file_path against the hook's cwd FIRST — otherwise
# `dirname` of a relative path (e.g. "PLAN-x.md" → ".") never equals an absolute
# workspace_root, silently bypassing the root-artifact guard below. The hook JSON
# carries `cwd`; if it is absent, fall back to $PWD.
abs_file_path="$file_path"
case "$file_path" in
  /*) ;;  # already absolute — use as-is
  *)
    hook_cwd=$(echo "$input" | jq -r '.cwd // empty')
    [ -n "$hook_cwd" ] || hook_cwd="$PWD"
    abs_file_path="${hook_cwd%/}/$file_path"
    ;;
esac

file_dir=$(dirname "$abs_file_path")
if [ -n "$CLAUDE_PROJECT_DIR" ]; then
  workspace_root="${CLAUDE_PROJECT_DIR%/}"
else
  workspace_root="$file_dir"
fi

if [[ "$file_dir" == "$workspace_root" && -d "$workspace_root/.claude-workspace" ]]; then
  # Unquoted regex var so bash 3.2 treats it as an ERE (quoting would force a literal match).
  # Also matches the bare TODO.md (optional second group).
  artifact_re='^(PLAN|AUDIT|TASK|TODO|INVESTIGATION)([-_][A-Za-z0-9._-]*)?\.md$'
  if [[ "$base_name" =~ $artifact_re ]]; then
    echo "🚫 BLOCKED: Cannot create loose task/plan artifact at the workspace root: $file_path" >&2
    echo "Protected pattern: (PLAN|AUDIT|TASK|TODO|INVESTIGATION)*.md directly in the workspace root" >&2
    echo "" >&2
    echo "Task artifacts belong in .claude-workspace/working/YYYY/MM/DD/<slug>/ —" >&2
    echo "create the task dir via scripts/agent-work.sh init." >&2
    exit 2
  fi
fi

# Allow the operation
exit 0
