#!/bin/bash
# Protect Sensitive Files Hook for Claude Code
# Blocks edits to sensitive files and directories

set -e

# Read JSON input from stdin
input=$(cat)

# Extract file path using jq
file_path=$(echo "$input" | jq -r '.tool_input.file_path // .tool_input.path // empty')

# Exit if no file path
if [ -z "$file_path" ]; then
  exit 0
fi

# Protected directory names — blocked only when they appear as a full
# path segment, so e.g. skills/docker-build/ is NOT mistaken for build/.
protected_dirs=(
  ".git"
  "node_modules"
  "dist"
  "build"
  ".next"
  "coverage"
)

# Protected files — lock files match by exact basename.
protected_files=(
  "package-lock.json"
  "yarn.lock"
  "pnpm-lock.yaml"
)

base_name=$(basename "$file_path")

# Block edits to files inside a protected directory (path-segment match,
# not substring — anchored by a leading "/" or the start of the path).
for dir in "${protected_dirs[@]}"; do
  if [[ "$file_path" == "$dir/"* || "$file_path" == *"/$dir/"* ]]; then
    echo "🚫 BLOCKED: Cannot modify file inside protected directory: $file_path"
    echo "Protected directory: $dir/"
    echo ""
    echo "If you need to modify this file, please do it manually."
    exit 2  # Exit code 2 blocks the operation
  fi
done

# Block edits to protected lock files (exact basename match).
for f in "${protected_files[@]}"; do
  if [[ "$base_name" == "$f" ]]; then
    echo "🚫 BLOCKED: Cannot modify protected file: $file_path"
    echo "Protected pattern: $f"
    echo ""
    echo "If you need to modify this file, please do it manually."
    exit 2  # Exit code 2 blocks the operation
  fi
done

# Block edits to any .env* file (basename prefix match — covers
# .env, .env.local, .env.production, .env.example, …).
if [[ "$base_name" == .env* ]]; then
  echo "🚫 BLOCKED: Cannot modify protected file: $file_path"
  echo "Protected pattern: .env*"
  echo ""
  echo "If you need to modify this file, please do it manually."
  exit 2  # Exit code 2 blocks the operation
fi

# Block edits to production / populated values files. Documented in rules/NEVER.md.
# Pattern matches values.prod.yaml, values.prod.yml, *.populated.yaml, *.populated.yml.
if [[ "$base_name" == values.prod.yaml || "$base_name" == values.prod.yml ]]; then
  echo "🚫 BLOCKED: Cannot modify production values file: $file_path"
  echo "Protected pattern: values.prod.{yaml,yml}"
  echo ""
  echo "Production values changes require @react-specialist + @sre-orchestrator joint review"
  echo "and explicit user approval per rules/ASK.md."
  echo "If this is a legitimate change, edit manually outside of an agent session."
  exit 2
fi

if [[ "$base_name" == *.populated.yaml || "$base_name" == *.populated.yml ]]; then
  echo "🚫 BLOCKED: Cannot modify populated (rendered-with-secrets) values file: $file_path"
  echo "Protected pattern: *.populated.{yaml,yml}"
  echo ""
  echo "These files are generated by Cloud Run bootstrap scripts (e.g., createSkNextSecrets.sh)"
  echo "and contain rendered secrets. They are gitignored and must never be hand-edited."
  exit 2
fi

# Block edits to generated router/network configs (may contain private keys + PSKs).
if [[ "$file_path" == *"/output/"* && "$base_name" == *.rsc ]]; then
  echo "🚫 BLOCKED: Cannot modify generated network config: $file_path"
  echo "Protected pattern: */output/*.rsc"
  echo ""
  echo "These files are generated by scripts/generate-*.sh and contain secrets."
  echo "Re-run the generator script instead of hand-editing."
  exit 2
fi

# Block edits to Terraform state files.
if [[ "$base_name" == terraform.tfstate || "$base_name" == terraform.tfstate.backup || "$base_name" == *.tfstate || "$base_name" == *.tfstate.backup ]]; then
  echo "🚫 BLOCKED: Cannot modify Terraform state: $file_path"
  echo "Protected pattern: *.tfstate(.backup)?"
  echo ""
  echo "Live infrastructure state is managed by 'terraform apply'; never edit by hand."
  exit 2
fi

# Allow the operation
exit 0

