package api

import (
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/atretyak1985/swarmery/tools/swarmery/internal/taskdir"
)

// TestMintedCardReadmeSatisfiesTheLifecycleContract is the second compat anchor for
// generated task dirs (the first is in internal/wsingest, over the parser).
//
// The lifecycle actions — pause, resume, archive — rewrite a task dir's README
// status line in place. If a GENERATED README carries no line cardStatusRe matches,
// upsertCardStatus falls back to inserting one after the H1, which is tolerable but
// hides a real question: does the file the daemon writes speak the format the daemon
// reads? This asserts it does, from the actual generated bytes.
func TestMintedCardReadmeSatisfiesTheLifecycleContract(t *testing.T) {
	dir, err := taskdir.MintMicroPlan(t.TempDir(), "p", taskdir.Card{
		ExternalID: "T-42", Title: "Fix the janitor sweep", Prompt: "do the thing",
	}, time.Date(2026, 8, 17, 9, 0, 0, 0, time.UTC))
	if err != nil {
		t.Fatalf("MintMicroPlan: %v", err)
	}
	raw, err := os.ReadFile(filepath.Join(dir, "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	readme := string(raw)

	if !cardStatusRe.MatchString(readme) {
		t.Fatalf("the generated README has no status line the lifecycle can rewrite:\n%s", readme)
	}
	if !cardH1Re.MatchString(readme) {
		t.Errorf("the generated README has no H1:\n%s", readme)
	}

	// A pause rewrites the value in place rather than inserting a second line.
	paused := upsertCardStatus(readme, "paused")
	if strings.Count(paused, "**Status**") != 1 {
		t.Errorf("pause duplicated the status line:\n%s", paused)
	}
	if !strings.Contains(paused, "- **Status**: paused") {
		t.Errorf("pause did not take:\n%s", paused)
	}
	// And back again, so the round trip is stable.
	if resumed := upsertCardStatus(paused, "active"); !strings.Contains(resumed, "- **Status**: active") {
		t.Errorf("resume did not take:\n%s", resumed)
	}
}

// TestUpsertCardStatusInsertsTheCanonicalMarker: a card with no status line (a
// hand-made task dir) gets one inserted after its H1, spelled the way every
// writer spells it — `- **Status**: <v>`, the marker agent-work.sh init writes
// and the core SessionStart hooks read. A legacy **Статус** card is edited in
// place with its label kept: readers accept both, writers add only the
// canonical one.
func TestUpsertCardStatusInsertsTheCanonicalMarker(t *testing.T) {
	got := upsertCardStatus("# Hand-made task\n\nsome prose\n", "paused")
	if want := "# Hand-made task\n\n- **Status**: paused\n\nsome prose\n"; got != want {
		t.Errorf("insert after the H1:\n got %q\nwant %q", got, want)
	}
	if got := upsertCardStatus("no heading at all\n", "done"); !strings.HasPrefix(got, "- **Status**: done\n") {
		t.Errorf("insert at the top when there is no H1:\n%s", got)
	}
	legacy := upsertCardStatus("# Old card\n\n- **Статус**: active · **Ціль**: keep me\n", "done")
	if want := "# Old card\n\n- **Статус**: done · **Ціль**: keep me\n"; legacy != want {
		t.Errorf("a legacy label must be kept and only its value replaced:\n got %q\nwant %q", legacy, want)
	}
}

// TestMicroPlanChipsResolveBothWays: the card and its micro-plan are one unit of
// work seen from two pages, so each side has to be able to name the other. Without
// both ids in the DTOs the relationship exists only in a path column nobody renders.
func TestMicroPlanChipsResolveBothWays(t *testing.T) {
	srv, db, taskID, planDir := epicFixture(t)

	// A board card that materialized THIS plan dir at dispatch.
	mustExecEpics(t, db, `INSERT INTO tasks (project_id, title, prompt, status, created_at,
		source, external_id, board_column, workspace_dir)
		VALUES (1,'the card','p','queued','2026-07-24T00:00:00Z','queue','T-42','todo',?)`,
		filepath.Dir(planDir))

	// Plans side: the epic names the card.
	e := firstEpic(t, srv)
	if e.CardExternalID == nil || *e.CardExternalID != "T-42" {
		t.Errorf("epic.cardExternalId = %v, want T-42", e.CardExternalID)
	}

	// Board side: the card names the plan.
	resp, err := http.Get(srv.URL + "/api/board/tasks?projectId=1")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	var board []struct {
		ExternalID     string  `json:"externalId"`
		PlanExternalID *string `json:"planExternalId"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&board); err != nil {
		t.Fatal(err)
	}
	var found bool
	for _, tk := range board {
		if tk.ExternalID != "T-42" {
			continue
		}
		found = true
		if tk.PlanExternalID == nil || *tk.PlanExternalID != "2026-07-24-my-epic" {
			t.Errorf("card.planExternalId = %v, want the epic's external id", tk.PlanExternalID)
		}
	}
	if !found {
		t.Fatal("the card is not on the board")
	}
	_ = taskID
}

// A hand-written plan has no card, and a card with no micro-plan has no plan: both
// sides must render nothing rather than something wrong.
func TestMicroPlanChipsAbsentWithoutAMicroPlan(t *testing.T) {
	srv, db, _, _ := epicFixture(t)
	mustExecEpics(t, db, `INSERT INTO tasks (project_id, title, prompt, status, created_at,
		source, external_id, board_column)
		VALUES (1,'a plain card','p','queued','2026-07-24T00:00:00Z','queue','T-99','todo')`)

	if got := firstEpic(t, srv).CardExternalID; got != nil {
		t.Errorf("epic.cardExternalId = %v, want null for a hand-written plan", *got)
	}
}
