-- Diff proposals for agent definition files, generated by internal/improve.
-- Lifecycle: proposed → approved → applied | rejected; failed is terminal-retriable.
CREATE TABLE agent_change_proposals (
  id                INTEGER PRIMARY KEY,
  recommendation_id INTEGER REFERENCES recommendations(id) ON DELETE SET NULL,
  agent             TEXT NOT NULL,           -- registry key (normalized)
  agent_path        TEXT NOT NULL,           -- absolute source path at generation time
  base_sha256       TEXT NOT NULL,           -- sha256 of agent file content the diff was made against
  diff              TEXT NOT NULL,           -- unified diff
  rationale         TEXT NOT NULL,           -- model's per-hunk explanation
  status            TEXT NOT NULL DEFAULT 'proposed'
                    CHECK (status IN ('proposed','approved','applied','rejected','failed')),
  error             TEXT,                    -- populated when status='failed'
  pr_url            TEXT,                    -- populated by phase 4 apply
  created_at        TEXT NOT NULL,
  decided_at        TEXT
);
CREATE INDEX idx_agent_proposals_agent ON agent_change_proposals(agent);
-- "one open proposal per agent" enforced in code (partial unique indexes on
-- status sets are brittle across migrations): SELECT ... WHERE agent=? AND status IN ('proposed','approved')
